### ISSUE TITLE
Missing ReadMe file

### ISSUE THREAD

**Issue by GregoirePetit** [thomassutter/mmodeecho#6]
Hi Thomas,
Thanks for uploading the code. Could you add the ReadMe file of the multimodalecho folder? I have some trouble to figure out how it runs.
Many thanks in advance,
Grégoire

**Comment by thomassutter** [comment]
Hi Gregoire,
What would you like to run? The multimodalecho is only for producing the plots and collecting the computed results.
(Sorry for my late reply)

Best,
Thomas

**Comment by GregoirePetit** [comment]
Hi Thomas,
Thanks for the reply.
I'd like to run the entire pipeline, but I can't find the corresponding ReadMe you're referring at the end of the root ReadMe.
I can only find the echonet ReadMe, not the one that explains how to use your code to extract M-modes pictures, then predict the EF from those images, then assess the cardiomyopathy. Perhaps I missed something.
Many thanks in advance,
Grégoire
